# Generated by Django 4.1.3 on 2022-12-01 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoice", name="id",),
        migrations.AlterField(
            model_name="invoice", name="price", field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="reference",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Reference number should be numbers-numbers",
                        regex="/^\\d-?\\d$/",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="invoice", name="unpaid", field=models.FloatField(max_length=20),
        ),
    ]
