# Generated by Django 4.1.3 on 2022-12-05 19:20

from django.db import migrations, models
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson_request",
            name="DurationOfLesson",
            field=models.PositiveIntegerField(
                choices=[
                    (15, "15 minutes"),
                    (30, "30 minutes"),
                    (45, "45 minutes"),
                    (60, "60 minutes"),
                    (75, "75 minutes"),
                    (90, "90 minutes"),
                    (105, "105 minutes"),
                    (120, "120 minutes"),
                ],
                validators=[lessons.models.validate_nonzero],
            ),
        ),
    ]
