# Generated by Django 4.1.3 on 2022-11-20 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson_request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("availableDays", models.CharField(max_length=3)),
                ("availableTimes", models.CharField(max_length=255)),
                ("numberOfLessons", models.PositiveIntegerField()),
                ("IntervalBetweenLessons", models.PositiveIntegerField()),
                ("DurationOfLesson", models.PositiveIntegerField()),
                ("LearningObjectives", models.CharField(max_length=255)),
                ("AdditionalNotes", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username must be an Email",
                        regex="[a-z0-9]+@[a-z]+\\.[a-z]{2,3}",
                    )
                ],
            ),
        ),
    ]
