# Generated by Django 4.1.3 on 2022-12-02 23:36

from django.db import migrations, models
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson_request",
            name="DurationOfLesson",
            field=models.PositiveIntegerField(
                choices=[
                    (15, "15 minutes"),
                    (30, "30 minutes"),
                    (45, "45 minutes"),
                    (60, "60 minutes"),
                    (75, "75 minutes"),
                    (90, "90 minutes"),
                    (105, "105 minutes"),
                    (120, "120 minutes"),
                    (135, "135 minutes"),
                    (150, "150 minutes"),
                    (165, "165 minutes"),
                    (180, "180 minutes"),
                    (195, "195 minutes"),
                    (210, "210 minutes"),
                    (225, "225 minutes"),
                    (240, "240 minutes"),
                ],
                validators=[lessons.models.validate_nonzero],
            ),
        ),
    ]
