# Generated by Django 3.2.5 on 2022-11-23 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be an Email', regex='[a-z0-9]+@[a-z]+\\.[a-z]{2,3}')]),
        ),
    ]
