# Generated by Django 4.1.3 on 2022-12-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_lesson_request_durationoflesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson_request",
            name="Fulfilled",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
