# Generated by Django 4.1.3 on 2022-11-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_alter_lesson_request_additionalnotes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson_request",
            name="AdditionalNotes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lesson_request",
            name="LearningObjectives",
            field=models.TextField(blank=True),
        ),
    ]
