# Generated by Django 4.1.3 on 2022-12-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_alter_lesson_request_fulfilled"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoice", name="student",),
        migrations.AddField(
            model_name="invoice",
            name="lesson",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.lesson_request",
            ),
        ),
    ]
