# Generated by Django 4.1.3 on 2022-11-28 17:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_alter_lesson_request_additionalnotes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson_request",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=80,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username must be an Email",
                        regex="[a-z0-9]+@[a-z]+\\.[a-z]{2,3}",
                    )
                ],
            ),
        ),
    ]
