# Generated by Django 4.1.3 on 2022-12-03 15:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_alter_invoice_creation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="creation_date",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=django.utils.timezone.now
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="update_date",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=django.utils.timezone.now
                    )
                ]
            ),
        ),
    ]
